filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              container.labels.collect_logs_with_filebeat: "true"
          config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              multiline:
                pattern: '^\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}\.\d{3}'
                negate: true
                match: after
              processors:
                - decode_json_fields:
                    when.equals:
                      docker.container.labels.decode_log_event_to_json_object: "true"
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true
                - add_fields:
                    fields:
                      application_name: "${data.docker.container.labels.application_name}"

output.logstash:
  hosts: "logstash:5044"