version: '3.7'

services:
  spring:
    build: ../spring
    container_name: spring
    networks:
      - elk-network
    ports:
      - "8080:8080"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
      application_name: "spring"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.1
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ../filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro       # Configuration file
      - fb_data:/usr/share/filebeat/data:rw                                # Persistence data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
    networks:
      - elk-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network
    volumes:
      - es_data:/usr/share/elasticsearch/data/
      - ../elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    networks:
      - elk-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ../kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.1
    container_name: logstash
    networks:
      - elk-network
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ../logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ../logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: "bridge"

volumes:
  es_data:
  ls_data:
  kb_data:
  fb_data: